[package]
name = "luna-bundle"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[dependencies]
blake3 = "1.8"
ed25519-dalek = { version = "2.1", features = ["std"] }
luna-common = { path = "../luna-common" }
serde = { version = "1.0", features = ["derive"] }
tar = "0.4"
toml = "0.9"
zstd = "0.13"
