[package]
name = "project-luna"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[dependencies]

[workspace]
resolver = "2"
members = [
  "components/luna-common",
  "components/luna-fs",
  "components/luna-root-mapping",
  "components/luna-namespace",
  "components/luna-config",
  "components/luna-security",
  "components/luna-state",
  "components/luna-event",
  "components/luna-bundle",
  "components/luna-app-manager",
  "components/luna-system-manager",
  "components/luna-update-manager",
  "components/luna-device-manager",
  "components/luna-kernel-manager",
  "components/luna-system-runtime",
  "components/luna-user-session",
  "components/luna-app-runtime",
  "components/luna-login",
  "components/luna-cli",
]
