[workspace]
resolver = "2"
members = [
  "components/system/luna-common",
  "components/system/luna-fs",
  "components/system/luna-root-mapping",
  "components/system/luna-namespace",
  "components/system/luna-config",
  "components/system/luna-security",
  "components/system/luna-state",
  "components/system/luna-event",
  "components/system/luna-bundle",
  "components/system/luna-app-manager",
  "components/system/luna-system-manager",
  "components/system/luna-update-manager",
  "components/system/luna-device-manager",
  "components/system/luna-kernel-manager",
  "components/system/luna-system-runtime",
  "components/system/luna-user-session",
  "components/system/luna-app-runtime",
  "components/system/luna-cli",
  "components/system/luna-audio",
  "components/system/luna-network",
  "components/system/luna-bluetooth",
  "components/system/luna-files",
  "tools/build-progress",
]
