//! Persistent state contracts for Project Luna.
use std::collections::BTreeMap;
use std::fmt;
#[derive(Clone, Debug, Eq, PartialEq, Ord, PartialOrd, Hash)] pub struct StateKey(String);
impl StateKey { pub fn new(value: impl Into<String>) -> Self { Self(value.into()) } pub fn as_str(&self)->&str{&self.0} }
#[derive(Clone, Debug, Eq, PartialEq)] pub struct StateValue(Vec<u8>);
impl StateValue { pub fn new(value: impl Into<Vec<u8>>)->Self{Self(value.into())} pub fn as_slice(&self)->&[u8]{&self.0} pub fn into_bytes(self)->Vec<u8>{self.0} }
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq, Ord, PartialOrd, Hash)] pub struct Revision(u64);
impl Revision { pub const fn initial()->Self{Self(0)} pub const fn value(self)->u64{self.0} pub const fn next(self)->Self{Self(self.0.saturating_add(1))} }
#[derive(Clone, Debug, Eq, PartialEq)] pub enum StateMutation { Set(StateKey,StateValue), Remove(StateKey) }
#[derive(Clone, Debug, Default, Eq, PartialEq)] pub struct StateTransaction{mutations:Vec<StateMutation>}
impl StateTransaction { pub fn new()->Self{Self::default()} pub fn set(&mut self,key:StateKey,value:StateValue)->&mut Self{self.mutations.push(StateMutation::Set(key,value));self} pub fn remove(&mut self,key:StateKey)->&mut Self{self.mutations.push(StateMutation::Remove(key));self} pub fn is_empty(&self)->bool{self.mutations.is_empty()} pub fn mutations(&self)->&[StateMutation]{&self.mutations} }
#[derive(Clone, Debug, Eq, PartialEq)] pub enum StateError { InvalidKey, ReadOnly, RevisionConflict{expected:Revision,actual:Revision}, Storage(String) }
impl fmt::Display for StateError { fn fmt(&self,f:&mut fmt::Formatter<'_>)->fmt::Result{match self{Self::InvalidKey=>f.write_str("invalid state key"),Self::ReadOnly=>f.write_str("state store is read-only"),Self::RevisionConflict{expected,actual}=>write!(f,"state revision conflict: expected {}, actual {}",expected.value(),actual.value()),Self::Storage(m)=>write!(f,"state storage error: {m}")}} }
impl std::error::Error for StateError {}
pub trait StateStore { fn get(&self,key:&StateKey)->Result<Option<StateValue>,StateError>; fn set(&mut self,key:StateKey,value:StateValue)->Result<(),StateError>; fn remove(&mut self,key:&StateKey)->Result<(),StateError>; fn revision(&self)->Revision; fn transaction(&mut self,expected_revision:Revision,transaction:StateTransaction)->Result<Revision,StateError>; }
#[derive(Clone,Debug,Default)] pub struct MemoryStateStore{values:BTreeMap<StateKey,StateValue>,revision:Revision}
impl MemoryStateStore{pub fn new()->Self{Self::default()} fn valid(k:&StateKey)->Result<(),StateError>{if k.as_str().trim().is_empty()||k.as_str().contains(".."){Err(StateError::InvalidKey)}else{Ok(())}} fn apply(values:&mut BTreeMap<StateKey,StateValue>,tx:&StateTransaction)->Result<(),StateError>{for m in tx.mutations(){match m{StateMutation::Set(k,v)=>{Self::valid(k)?;values.insert(k.clone(),v.clone());},StateMutation::Remove(k)=>{Self::valid(k)?;values.remove(k);}}}Ok(())}}
impl StateStore for MemoryStateStore{fn get(&self,k:&StateKey)->Result<Option<StateValue>,StateError>{Self::valid(k)?;Ok(self.values.get(k).cloned())} fn set(&mut self,k:StateKey,v:StateValue)->Result<(),StateError>{let r=self.revision;let mut tx=StateTransaction::new();tx.set(k,v);self.transaction(r,tx).map(|_|())} fn remove(&mut self,k:&StateKey)->Result<(),StateError>{let r=self.revision;let mut tx=StateTransaction::new();tx.remove(k.clone());self.transaction(r,tx).map(|_|())} fn revision(&self)->Revision{self.revision} fn transaction(&mut self,expected:Revision,tx:StateTransaction)->Result<Revision,StateError>{if self.revision!=expected{return Err(StateError::RevisionConflict{expected,actual:self.revision})}else if tx.is_empty(){return Ok(self.revision)}let mut next=self.values.clone();Self::apply(&mut next,&tx)?;self.values=next;self.revision=self.revision.next();Ok(self.revision)}}
#[cfg(test)]mod tests{use super::*;#[test]fn round_trip(){let k=StateKey::new("a");let mut s=MemoryStateStore::new();s.set(k.clone(),StateValue::new(b"v".to_vec())).unwrap();assert_eq!(s.get(&k).unwrap().unwrap().as_slice(),b"v")}#[test]fn atomic_revision(){let mut s=MemoryStateStore::new();let r=s.revision();let mut t=StateTransaction::new();t.set(StateKey::new("a"),StateValue::new(b"1".to_vec())).set(StateKey::new("b"),StateValue::new(b"2".to_vec()));assert_eq!(s.transaction(r,t).unwrap(),r.next())}#[test]fn stale_is_rejected(){let mut s=MemoryStateStore::new();let stale=s.revision();s.set(StateKey::new("a"),StateValue::new(b"current".to_vec())).unwrap();let mut t=StateTransaction::new();t.set(StateKey::new("a"),StateValue::new(b"stale".to_vec()));assert!(matches!(s.transaction(stale,t),Err(StateError::RevisionConflict{..})));assert_eq!(s.get(&StateKey::new("a")).unwrap().unwrap().as_slice(),b"current")}#[test]fn invalid_key_does_not_mutate(){let mut s=MemoryStateStore::new();assert!(matches!(s.set(StateKey::new("../bad"),StateValue::new(vec![1])),Err(StateError::InvalidKey)));assert_eq!(s.revision(),Revision::initial())}}
