#!/bin/sh

mount -t proc proc /proc 2>/dev/null || true
mount -t sysfs sysfs /sys 2>/dev/null || true
mount -t devtmpfs devtmpfs /dev 2>/dev/null || true

printf '\n%s\n%s\n\n' \
    'Luna initramfs reached successfully.' \
    'The kernel was loaded by luna-boot and control reached /init.'

exec sh
