[package]
name = "luna-update-manager"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[lib]
path = "src/lib.rs"

[[bin]]
name = "luna-update-manager"
path = "src/main.rs"

[dependencies]
luna-common = { path = "../luna-common" }
luna-state = { path = "../luna-state" }
luna-system-manager = { path = "../luna-system-manager" }
